name: Docker CI

on:
  push:
    branches: ["humble"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: epflxplore/rover

jobs:
  delete-untagged-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps:
      - name: Delete all untagged images from repository
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
            token: ${{ secrets.PAT_TOKEN }}
            repository_owner: ${{ github.repository_owner }}
            owner_type: org
            repository: ${{ github.repository }}
            untagged_only: true

  build-and-push-image-amd64:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./docker_humble_desktop/Dockerfile
            context: .
            tag: humble-desktop
            platform: linux/amd64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check disk space
        run: df . -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          platforms: ${{ matrix.platform }}
          no-cache: true
          pull: true
          push: true

  build-and-push-image-arm64:
    runs-on: ubuntu-24.04-arm

    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./docker_humble_jetson/Dockerfile
            context: .
            tag: humble-jetson
            platform: linux/arm64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check disk space
        run: df . -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (arm64)
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          platforms: ${{ matrix.platform }}
          no-cache: true
          pull: true
          push: true
