name: Docker CI

on:
  push:
    branches: ["humble"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: epflxplore/cs

jobs:
  delete-untagged-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps:
      - name: Delete all untagged images from repository
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
            token: ${{ secrets.PAT_TOKEN }}
            repository_owner: ${{ github.repository_owner }}
            owner_type: org
            repository: ${{ github.repository }}
            untagged_only: true

  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: "true"
          token: ${{ secrets.PAT_TOKEN }}

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf package-lock.json
          npm install
          npm ci
        working-directory: ./cs_ws/src/control_station_pkg/control_station_pkg/csApp/frontend

      # build and test the apps
      - name: build
        run: |
          npm run build
          npm run test --passWithNoTests
        working-directory: ./cs_ws/src/control_station_pkg/control_station_pkg/csApp/frontend
        env:
          CI: false

  build-and-push-image:
    runs-on: ubuntu-24.04

    # build docker image and push to GHCR (amd64 only)
    # only if the app build and test successfully
    needs: [build_test]

    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./docker_humble_desktop/Dockerfile
            context: .
            tag: humble-desktop
            platform: linux/amd64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check disk space
        run: df . -h

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (amd64)
        id: build
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}-amd64-temp
          platforms: ${{ matrix.platform }}
          no-cache: true
          pull: true
          push: true

    outputs:
      image_digest: ${{ steps.build.outputs.digest }}

  build-and-push-image-arm64:
    runs-on: ubuntu-24.04-arm

    # build docker image and push to GHCR (arm64 only)
    needs: [build_test]

    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./docker_humble_desktop/Dockerfile
            context: .
            tag: humble-desktop
            platform: linux/arm64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check disk space
        run: df . -h

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (arm64)
        id: build
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}-arm64-temp
          platforms: ${{ matrix.platform }}
          no-cache: true
          pull: true
          push: true

    outputs:
      image_digest: ${{ steps.build.outputs.digest }}

  create-and-push-manifest:
    runs-on: ubuntu-24.04
    needs: [build-and-push-image, build-and-push-image-arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:humble-desktop \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push-image.outputs.image_digest }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push-image-arm64.outputs.image_digest }}
          # Optionally annotate and clean up temporary tags
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:humble-desktop